blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.views import BlogListView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls', namespace='service')),
    path('', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path

from service.views import CreateMailingView, ListMailingView, UpdateMailingView, DeleteMailingView, \
    DetailMailingView, CreateClientView, ListClientView, DeleteClientView, MailingLogListView, DeleteMailingLogView, \
    DetailMailingLogView

app_name = 'service'

urlpatterns = [
    path('create_mailing/', CreateMailingView.as_view(), name='create_mailing'),
    path('list_mailing/', ListMailingView.as_view(), name='list_mailing'),
    path('update_mailing/<int:pk>/', UpdateMailingView.as_view(), name='update_mailing'),
    path('delete_mailing/<int:pk>/', DeleteMailingView.as_view(), name='delete_mailing'),
    path('detail_mailing/<int:pk>/', DetailMailingView.as_view(), name='detail_mailing'),
    path('create_client/', CreateClientView.as_view(), name='create_client'),
    path('clients_list/', ListClientView.as_view(), name='clients_list'),
    path('delete_client/<int:pk>/', DeleteClientView.as_view(), name='delete_client'),
    path('mailing_logs_list/', MailingLogListView.as_view(), name='mailing_logs_list'),
    path('mailing_log_detail/<int:pk>/', DetailMailingLogView.as_view(), name='mailing_log_detail'),
    path('delete_mailing_log/<int:pk>/', DeleteMailingLogView.as_view(), name='delete_mailing_log'),
]

service/models.py
from datetime import datetime

from django.conf import settings
from django.db import models

NULLABLE = {'null': True, 'blank': True}


# Create your models here.
class Client(models.Model):
    email = models.EmailField(verbose_name='электронная почта')
    surname = models.CharField(max_length=20, verbose_name='фамилия')
    name = models.CharField(max_length=20, verbose_name='имя')
    middle_name = models.CharField(max_length=20, verbose_name='отчество', **NULLABLE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f'Клиент: {self.email}.'

    def save(self, *args, **kwargs):
        if Client.objects.filter(user=self.user, email=self.email).exists():
            raise ValueError
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Mailing(models.Model):
    REGULARITY_CHOICES = (
        ('daily', 'Раз в день'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
    )

    STATUS_CHOICES = (
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('completed', 'Завершена'),
    )

    mailing_time = models.DateTimeField(verbose_name='время рассылки')
    regularity = models.CharField(max_length=10, choices=REGULARITY_CHOICES, verbose_name='периодичность')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='created', verbose_name='статус рассылки')
    clients = models.ManyToManyField(Client, related_name='mailings', verbose_name='клиенты')
    mail_theme = models.TextField(max_length=100, verbose_name='тема письма')
    mail_text = models.TextField(max_length=350, verbose_name='тело письма')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь')
    is_active = models.BooleanField(default=True, verbose_name='признак активности')

    def __str__(self):
        return f'Рассылка {self.mail_theme}.'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class MailingLog(models.Model):
    STATUS_CHOICES = (
        ('success', 'Успешно'),
        ('failed', 'Не удалось'),
    )

    timestamp = models.DateTimeField(default=datetime.now, verbose_name='дата и время попытки')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, verbose_name='статус попытки')
    server_response = models.TextField(verbose_name='ответ почтового сервера', **NULLABLE)
    client = models.ManyToManyField(Client, related_name='logs', verbose_name='клиент')
    mailing_list = models.ForeignKey(Mailing, on_delete=models.CASCADE, related_name='logs',
                                     verbose_name='рассылка')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f'Лог: "{self.mailing_list}"'

    class Meta:
        verbose_name = 'Лог рассылки'
        verbose_name_plural = 'Логи рассылок'

service/forms.py
from django import forms

from service.models import Mailing, Client


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'clients':
                continue
            else:
                field.widget.attrs['class'] = 'form-control'


class CreateMailingForm(StyleFormMixin, forms.ModelForm):
    mailing_time = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={
                'class': 'form-control',
                'type': 'datetime-local'
            }
        ),
        label='Дата и время рассылки'
    )

    clients = forms.ModelMultipleChoiceField(
        queryset=Client.objects.none(),
        widget=forms.CheckboxSelectMultiple,
        label='Клиенты'
    )

    mail_theme = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Введите текст'}),
        label='Тема сообщения'
    )

    mail_text = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Введите текст'}),
        label='Текст сообщения'
    )

    class Meta:
        model = Mailing
        exclude = ('status', 'user', 'is_active')

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(user=user)


class UpdateMailingForm(StyleFormMixin, forms.ModelForm):

    mailing_time = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={
                'class': 'form-control',
                'type': 'datetime-local'
            }
        ),
        label='Дата и время рассылки'
    )

    clients = forms.ModelMultipleChoiceField(
        queryset=Client.objects.none(),
        widget=forms.CheckboxSelectMultiple,
        label='Клиенты'
    )

    class Meta:
        model = Mailing
        fields = ('mailing_time', 'regularity', 'clients')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(user=user)


class CreateClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('user',)

service/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView, ListView

from service.forms import CreateMailingForm, UpdateMailingForm, CreateClientForm
from service.models import Mailing, Client, MailingLog


# Create your views here.

@method_decorator(login_required(login_url='users:login'), name='dispatch')
class CreateMailingView(CreateView):
    model = Mailing
    form_class = CreateMailingForm
    success_url = reverse_lazy('service:list_mailing')

    def get(self, request, **kwargs):
        form = self.form_class(self.request.user, request.POST)
        context = {
            'form': form,
        }
        clients = Client.objects.filter(user=self.request.user)
        context['clients'] = clients
        return render(request, 'service/mailing_form.html', context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.user, request.POST)

        if form.is_valid():
            clients = form.cleaned_data.get('clients')
            if not clients:
                form.add_error('clients', 'Выберите хотя бы одного клиента.')
            mailing = form.save(commit=False)
            mailing.user = self.request.user
            mailing.save()
            form.save_m2m()
            return redirect(self.success_url)

        else:
            return render(request, 'service/no_client.html')


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class UpdateMailingView(UpdateView):
    model = Mailing
    form_class = UpdateMailingForm
    success_url = reverse_lazy('service:list_mailing')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        clients = Client.objects.filter(user=self.request.user)
        context['clients'] = clients
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class ListMailingView(ListView):
    model = Mailing
    template_name = 'service/mailing_list.html'

    def get_queryset(self):
        return Mailing.objects.filter(user=self.request.user)


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class DetailMailingView(DetailView):
    model = Mailing
    template_name = 'service/mailing_detail.html'


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class DeleteMailingView(DeleteView):
    model = Mailing
    template_name = 'service/mailing_confirm_delete.html'
    success_url = reverse_lazy('service:list_mailing')


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class CreateClientView(CreateView):
    model = Client
    form_class = CreateClientForm
    success_url = reverse_lazy('service:clients_list')

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            try:
                client = form.save(commit=False)
                client.user = self.request.user
                client.save()
            except ValueError:
                return render(request, 'service/client_exists.html')
            else:
                return redirect(self.success_url)


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class ListClientView(ListView):
    model = Client
    template_name = 'service/clients_list.html'

    def get_queryset(self):
        return Client.objects.filter(user=self.request.user)


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class DeleteClientView(DeleteView):
    model = Client
    template_name = 'service/client_confirm_delete.html'
    success_url = reverse_lazy('service:clients_list')


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class MailingLogListView(ListView):
    model = MailingLog
    template_name = 'service/mailing_logs_list.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return self.model.objects.all
        else:
            return self.model.objects.filter(user=self.request.user)


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class DetailMailingLogView(DetailView):
    model = MailingLog
    template_name = 'service/mailing_log_detail.html'


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class DeleteMailingLogView(DeleteView):
    model = MailingLog
    template_name = 'service/log_confirm_delete.html'
    success_url = reverse_lazy('service:mailing_logs_list')

service/templates/service/client_confirm_delete.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить пользователя "{{ object.email }}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a onclick="goBack()" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
function goBack() {
  window.history.back();
}


</script>
{% endblock %}

service/templates/service/client_form.html
{% extends 'service/index.html' %}
{% block content %}
<div class="col-12">
   <div class="col-md-6 mx-auto">
      <div class="card">
         <div class="card-header">Добавление клиента.</div>
         <div class="card-body">
            <form method="post" enctype="multipart/form-data">
               {% csrf_token %}
               {{ form.as_p }}
               <button type="submit" name="add_client" class="btn btn-success mt-3">
                  Добавить
               </button>
               <a onclick="goBack()" class="btn btn-warning mt-3">Отмена</a>
            </form>
         </div>
      </div>
   </div>
</div>
<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock %}

service/templates/service/clients_list.html
{% extends 'service/index.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Клиенты</h1>
</div>
<div class="col-12 mb-3">
    <a class="btn btn-outline-primary col-12" href="{% url 'service:create_client' %}">Добавить клиента</a>
</div>
<div class="row text-center mt-3">
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Клиент "{{ object.email }}"</h4>
            </div>
            <div class="card-body">
                {% if object.middle_name %}
                   <div class="card-text">ФИО: {{ object.surname }} {{ object.name }} {{ object.middle_name }}.</div>
                {% else %}
                   <div class="card-text">ФИ: {{ object.surname }} {{ object.name }}.</div>
                {% endif %}
                <a href="{% url 'service:delete_client' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-danger mt-3">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

service/templates/service/index.html
<!doctype html>
{% load static %}
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>SkyProMail</title>
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
   </head>
   <body>
      {% include 'service/includes/inc_main_menu.html' %}
      <div class="container">
         {% block content %}
         {% endblock %}
         <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
               <div class="col-12 col-md">
                  SkyProMail
                  <small class="d-block mb-3 text-muted">&copy; 2023</small>
               </div>
            </div>
         </footer>
      </div>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
   </body>
</html>

service/templates/service/log_confirm_delete.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить отчет "{{ object }}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a onclick="goBack()" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
function goBack() {
  window.history.back();
}


</script>
{% endblock %}

service/templates/service/mailing_confirm_delete.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить рассылку "{{ object.mail_theme }}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a onclick="goBack()" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
function goBack() {
  window.history.back();
}

</script>
{% endblock %}

service/templates/service/mailing_detail.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Рассылка "{{ object.mail_theme }}"
                    </h3>
                    <h3 class="card-title">
                        {% if object.user %}
                            Владелец рассылки: @{{ object.user }}
                        {% endif %}
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        Cообщение: {{ object.mail_text }}
                    </p>
                    <p>
                        Кому:
                        {% for client in mailing.clients.all  %}
                        {{ client.email }};
                        {% endfor %}
                    </p>
                </div>
                <div class="card-footer" style="display: flex; justify-content: space-between; align-items: center;">
                    <div>
                        Дата и время рассылки: {{ object.mailing_time }}
                        {% if object.last_update %}
                        Дата последнего изменения: {{ object.last_update }}
                        {% endif %}
                    </div>
                    <div class="right-button">
                        <a onclick="goBack()" class="btn btn-warning mt-2">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock %}

service/templates/service/mailing_form.html
{% extends 'service/index.html' %}
{% block content %}
<div class="col-12">
   <div class="col-md-6 mx-auto">
      <div class="card">
         {% if object %}
         <div class="card-header">Изменение рассылки "{{ object.mail_theme }}".</div>
         {% else %}
         <div class="card-header">Создание рассылки.</div>
         {% endif %}
         <div class="card-body">
            <form method="post" enctype="multipart/form-data">
               {% csrf_token %}
               {{ form.mailing_time.label_tag }}{{ form.mailing_time }}
               {% if clients.count == 0 %}
               <div class="mt-3">
                  {{ form.clients.label_tag }}
               </div>
               <div class="alert alert-info">
                  Клиенты не обнаружены.
               </div>
               <a href="{% url 'service:create_client' %}" class="btn btn-primary">Добавить клиента</a>
               {% else %}
               <div class="mt-3">
                  {{ form.clients.label_tag }}{{ form.clients }}
               </div>
               {% endif %}
               <div class="mt-3">
                  {{ form.regularity.label_tag }}{{ form.regularity }}
               </div>
               <div class="mt-3">
                  {{ form.mail_theme.label_tag }}{{ form.mail_theme }}
               </div>
               <div class="mt-3">
                  {{ form.mail_text.label_tag }}{{ form.mail_text }}
               </div>
               <button type="submit" name="save_mailing" class="btn btn-success mt-3">
               {% if object %}
                  Сохранить
               {% else %}
                  Создать
               {% endif %}
               </button>
               {% if clients.count > 1 %}
               <a id="select-all-clients" type="submit" name="save_clients" class="btn btn-primary custom-button mt-3">
                  Выбрать всех клиентов
               </a>
               {% endif %}
               {% if clients.count > 0 %}
                  <a href="{% url 'service:create_client' %}" class="btn btn-primary mt-3">Добавить клиента</a>
               {% endif %}
               {% if clients.count <= 1 %}
                  <a onclick="goBack()" class="btn btn-warning mt-3">Отмена</a>
               {% else %}
                  <a onclick="goBack()" class="btn btn-warning mt-2">Отмена</a>
               {% endif %}
            </form>
         </div>
      </div>
   </div>
</div>

<script>
   document.addEventListener("DOMContentLoaded", function () {
       const selectAllClientsButton = document.getElementById("select-all-clients");
       const clientCheckboxes = document.querySelectorAll('input[name="clients"]');

       selectAllClientsButton.addEventListener("click", function (event) {
           event.preventDefault();

           for (const checkbox of clientCheckboxes) {
               checkbox.checked = true;
           }
       });
   });
</script>

<script>
function goBack() {
  window.history.back();
}
</script>

<style>
   .custom-button {
   color: white !important;
   }
</style>
{% endblock %}

service/templates/service/mailing_list.html
{% extends 'service/index.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылки</h1>
</div>
<div class="row text-center mt-3">
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Рассылка "{{ object.mail_theme }}"</h4>
            </div>
            <div class="card-body">
                <div class="card-text">Дата рассылки: {{ object.mailing_time }}.</div>
                <a href="{% url 'service:detail_mailing' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary mt-3">Подробнее</a>
                <a href="{% url 'service:update_mailing' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-warning mt-3">Изменить</a>
                <a href="{% url 'service:delete_mailing' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-danger mt-3">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

service/templates/service/mailing_log_detail.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        {{ object }}
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        Дата и время попытки: {{ object.timestamp }}
                    </p>
                    <p>
                        Cтатус попытки: "{{ object.status }}"
                    </p>
                    {% if object.server_response %}
                    <p>
                        Ответ почтового сервера {{ object.server_response }}
                    </p>
                    {% endif %}
                </div>
                <div class="card-footer" style="display: flex; justify-content: space-between; align-items: center;">
                    <div class="card-text">Создатель: {{ object.user }}</div>
                    <div class="right-button">
                        <a onclick="goBack()" class="btn btn-warning mt-2">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock %}

service/templates/service/mailing_logs_list.html
{% extends 'service/index.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Отчеты</h1>
</div>
<div class="row text-center mt-3">
    {% for object in object_list %}
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object }}</h4>
            </div>
            <div class="card-body ms-auto">
                <a href="{% url 'service:mailing_log_detail' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary ms-auto">Подробнее</a>
                <a href="{% url 'service:delete_mailing_log' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-danger ms-auto">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

service/templates/service/mailing_message.html
{% autoescape off %}
{{ object.mail_text }}
{% endblock %}
SkyProMail!
{% block reset_link %}
http://{{ domain }}
{% endautoescape %}

service/templates/service/no_client.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <p>Вы не выбрали ни одного клиента!</p>
                <a onclick="goBack()" class="btn btn-warning">Вернуться</a>
            </div>
        </div>
    </div>
</div>

<script>
function goBack() {
  window.history.back();
}


</script>
{% endblock %}