blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.views import BlogListView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls', namespace='service')),
    path('', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, ResetView, ResetDoneView, EmailVerifyView, EmailVerifyDoneView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/', ResetView.as_view(), name='reset'),
    path('done/', ResetDoneView.as_view(), name='done'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email_verify/', EmailVerifyView.as_view(), name='email_verify'),
    path('email_verify_done/<uidb64>/<token>/', EmailVerifyDoneView.as_view(), name='email_verify_done')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from service.models import NULLABLE


# Create your models here.
class User(AbstractUser):

    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)

    is_email_active = models.BooleanField(default=False, verbose_name='верификация по почте')
    is_active = models.BooleanField(default=True, verbose_name='признак активности')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class PasswordAltResetForm(forms.Form):
    email = forms.EmailField(
        label="Укажите вашу электронную почту",
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )

users/views.py
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, FormView

from users.forms import UserRegisterForm, PasswordAltResetForm
from users.models import User


# Create your views here.
class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')


class ResetView(FormView):
    model = User
    form_class = PasswordAltResetForm
    email_template_name = 'users/reset_email.html'
    template_name = 'users/reset_password.html'
    success_url = reverse_lazy('users:done')
    token_generator = default_token_generator

    def get(self, request, **kwargs):
        return render(request, self.template_name, {'form': self.form_class})

    @staticmethod
    def send_mail_for_reset(request, email, new_password):
        current_site = get_current_site(request)
        context = {
            'domain': current_site.domain,
            'new_password': new_password
        }
        message = render_to_string('users/reset_email.html', context=context)
        email = EmailMessage(
            'Восстановление пароля',
            message,
            to=[email],
        )
        email.send()

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = self.model.objects.get(email=email)
            if user:
                new_password = self.token_generator.make_token(user)[:10]
                user.set_password(new_password)
                user.save()
                self.send_mail_for_reset(request, email, new_password)
                return redirect(self.success_url)
            else:
                return render(request, 'users/email_verify_unsuccessful.html')


class ResetDoneView(PasswordResetDoneView):
    template_name = 'users/reset_done.html'
    title = "Сообщение отправлено!"


class EmailVerifyView(FormView):
    model = User
    email_template_name = "users/email_verify_message.html"
    template_name = 'users/email_verify_confirm.html'
    success_url = 'users/email_verify_sended.html'
    token_generator = default_token_generator

    @staticmethod
    def send_mail_for_verify(request, user, token_generator):
        current_site = get_current_site(request)
        context = {
            'user': user,
            'domain': current_site.domain,
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "token": token_generator.make_token(user),
        }
        message = render_to_string('users/email_verify_message.html', context=context)
        email = EmailMessage(
            'Подтверждение электронной почты',
            message,
            to=[user.email],
        )
        email.send()

    def get(self, request, **kwargs):
        return render(request, self.template_name)

    def post(self, request, **kwargs):
        user = request.user
        self.send_mail_for_verify(request, user, self.token_generator)
        return render(request, self.success_url)


class EmailVerifyDoneView(View):
    model = User
    template_name = 'users/email_verify_done.html'
    unsuccessful_template_name = 'users/email_verify_unsuccessful.html'
    anonim_template_name = 'users/email_verify_anonim.html'
    token_generator = default_token_generator

    @staticmethod
    def get_user(model, uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = model.objects.get(pk=uid)
        except (
                TypeError,
                ValueError,
                OverflowError,
                model.DoesNotExist,
                ValidationError,
        ):
            user = None
        return user

    def get(self, request, uidb64, token, **kwargs):
        user = request.user
        print(user.pk)

        if user.pk is None:
            return render(request, self.anonim_template_name)

        user_for_email_activation = self.get_user(self.model, uidb64)
        token_for_email_activation = self.token_generator.check_token(user, token)

        if user == user_for_email_activation and token_for_email_activation:
            user.is_email_active = True
            user.save()
            return render(request, self.template_name)
        else:
            return render(request, self.unsuccessful_template_name)

users/templates/users/email_verify_anonim.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Подтверждение электронной почты
                    </h3>
                </div>
                <div class="card-body">
                    Для подтверждения электронной почты, необходимо войти.
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/email_verify_confirm.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Подтверждение электронной почты
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                     <div class="card-text">
                    Чтобы отправить сообщение с ссылкой для подтверждения электронной почты, нажмите кнопку ниже.
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">
                        Отправить
                    </button>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/email_verify_done.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Подтверждение электронной почты
                    </h3>
                </div>
                <div class="card-body">
                    Электронная почта подтверждена!
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/email_verify_message.html
{% autoescape off %}
Добрый день! Пожалуйста, перейдите по ссылке ниже для подтверждения электронной почты:
{% block reset_link %}
http://{{ domain }}{% url 'users:email_verify_done' uidb64=uid token=token %}
{% endblock %}
RedDeadMail!
{% endautoescape %}

users/templates/users/email_verify_sended.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Подтверждение электронной почты
                    </h3>
                </div>
                <div class="card-body">
                    Ссылка для подтверждения Email адреса отправлена на вашу электронную почту!
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/email_verify_unsuccessful.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Подтверждение электронной почты
                    </h3>
                </div>
                <div class="card-body">
                    Ссылка повреждена, подтвердить электронную почту не удалось.
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Войти</button>
                    <a href="{% url 'users:reset' %}" type="submit" class="btn btn-primary">Забыл(а) пароль</a>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/reset_done.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Восстановление пароля
                    </h3>
                </div>
                <div class="card-body">
                    Ссылка для изменения пароля отправлена на вашу электронную почту!
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/reset_email.html
{% autoescape off %}
Добрый день! Вот ваш новый пароль: {{ new_password }}
Пожалуйста, перейдите по ссылке ниже для того, чтобы войти:
{% block link %}
http://{{ domain }}{% url 'users:login' %}
{% endblock %}
RedDeadMail!
{% endautoescape %}

users/templates/users/reset_password.html
{% extends 'service/index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Восстановление пароля
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}